version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - command: curl -u ${fc37a521b7425c533c2be1344acc6271f5bb07b7}: \
     -d build_parameters[nightwatch_pipeline]=deploy_docker \
     https://circleci.com/api/v1.1/project/<github>/<pavantekal>/<nightwatch_pipeline>/tree/<master>
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
