version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - run: 
          name: Trigger job 2
          command: |
              curl -X POST https://circleci.com/api/v1/project/pavantekal/nightwatch_pipeline/tree/master?circle-token='62d4520913868e413de72e1e2c006bcba4820519'
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
